name: ESPHome Wake Word Voice Assistants Bug Report
description: |-
  Report an issue with the ESPHome Wake Word Voice Assistant firmware provided by this repository,
  the web installer and the provided OTA updates.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs with the ESPHome Wake Word Voice Assistant firmware that is compiled and released
        from this repository. This includes flashing the firmware from the ESPHome projects page and the OTA updates that are provided.

        If you have taken control of the device in the ESPHome Builder, please report the issue in the main [ESPHome issue tracker][issues].

        [issues]: https://github.com/esphome/issues

  - type: textarea
    validations:
      required: true
    id: problem
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.

  - type: dropdown
    validations:
      required: true
    id: device
    attributes:
      label: Which device are you using?
      options:
        - esp32-s3-box
        - esp32-s3-box-lite
        - esp32-s3-box-3
        - m5stack-atom-echo

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Firmware Version
      description: >
        The version of the installed version. This is **NOT** the ESPHome version, but is in the format `25.2.1` for example.

  - type: textarea
    id: logs
    validations:
      required: true
    attributes:
      label: Logs
      description: Serial logs from the USB port are required
      render: txt

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
