name: Build minimal

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.4.0
    with:
      files: |
        m5stack-atom-echo/m5stack-atom-echo.minimal.factory.yaml
      esphome-version: 2025.5.0
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }}

  upload-to-release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs:
      - build-firmware
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          path: files

      - name: Copy file to output
        run: |-
          mkdir output
          version="${{ github.event.release.tag_name }}"
          cd "files/m5stack-atom-echo/$version"
          cp m5stack-atom-echo-esp32.factory.bin ../../../output/m5stack-atom-echo.minimal.factory.bin
          md5sum m5stack-atom-echo-esp32.factory.bin | head -c 32 > ../../../output/m5stack-atom-echo.minimal.factory.bin.md5

      - name: Upload files to release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: output/*
          tag_name: ${{ github.event.release.tag_name }}
